#DATABASE
spring.datasource:
  url: jdbc:mysql://localhost:3306/controlsystem?useSSL=true
  username: user123
  password: user123

spring.jpa:
  show-sql: true
  hibernate:
    ddl-auto: none
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      format_sql: true

#FLYWAY
spring.flyway:
  url: jdbc:mysql://localhost:3306?useSSL=true
  user: user123
  password: user123
  schemas: controlsystem

#SWAGGER
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method
#SECURITY
jwt:
  token:
    secret-key: control123system
    expire-length: 900000

